import React from 'react'
import { useGLTF } from '@react-three/drei'
import { createPathToVojta } from '@/Three/utils/paths'
import { VojtaType } from '@/Three/types'
import { useVojta } from '@/Three/hooks/useVojta'

const path = createPathToVojta(VojtaType.Robot)

export function Robot(props: any) {
  const { groupRef } = useVojta()

  const gltf: any = useGLTF(path)
  const { nodes, materials } = gltf

  return (
    <group {...props} position={[0, 0, 0]} ref={groupRef} dispose={null}>
      <mesh
        geometry={nodes.M_Mask_Hi_Body_Mat_0.geometry}
        material={materials.Body_Mat}
      />
      <mesh
        geometry={nodes.M_Head_Hi_Dark_Mat_0.geometry}
        material={materials.Dark_Mat}
      />
      <mesh
        geometry={nodes.M_Head_Hi_Body_Mat_0.geometry}
        material={materials.Body_Mat}
      />
      <mesh
        geometry={nodes.SK_Head_Hi_Kashima_Mat_0.geometry}
        material={materials.Kashima_Mat}
      />
      <mesh
        geometry={nodes.SK_Head_Hi_Dark_Mat_0.geometry}
        material={materials.Dark_Mat}
      />
      <mesh
        geometry={nodes.SK_Head_Hi_Dark_Mat_0_1.geometry}
        material={materials.Dark_Mat}
      />
      <mesh
        geometry={nodes.SK_Head_Hi_Eyes_Mat_0.geometry}
        material={materials.Eyes_Mat}
      />
      <mesh
        geometry={nodes.SK_Head_Neck_Hi_Wires_Mat1_0.geometry}
        material={materials.Wires_Mat1}
      />
      <mesh
        geometry={nodes.SK_Head_Neck_Hi_Dark_Mat_0.geometry}
        material={materials.Dark_Mat}
      />
      <mesh
        geometry={nodes.M_Chest_Hi_Body_Mat_0.geometry}
        material={materials.Body_Mat}
      />
      <mesh
        geometry={nodes.M_Chest_Hi_Dark_Mat_0.geometry}
        material={materials.Dark_Mat}
      />
      <mesh
        geometry={nodes.M_Chest_Hi_Kashima_Mat_0.geometry}
        material={materials.Kashima_Mat}
      />
      <mesh
        geometry={nodes.M_Torso_Hi_Body_Mat_0.geometry}
        material={materials.Body_Mat}
      />
      <mesh
        geometry={nodes.M_Torso_Hi_Dark_Mat_0.geometry}
        material={materials.Dark_Mat}
      />
      <mesh
        geometry={nodes.M_Torso_Hi_Rubber_Mat_0.geometry}
        material={materials.Rubber_Mat}
      />
      <mesh
        geometry={nodes.SK_Torso_Hi_Dark_Mat_0.geometry}
        material={materials.Dark_Mat}
      />
      <mesh
        geometry={nodes.SK_Torso_Hi_Wires_Mat1_0.geometry}
        material={materials.Wires_Mat1}
      />
      <mesh
        geometry={nodes.M_Pelvis_Hi_Body_Mat_0.geometry}
        material={materials.Body_Mat}
      />
      <mesh
        geometry={nodes.SK_Pelvis_Hi_Kashima_Mat_0.geometry}
        material={materials.Kashima_Mat}
      />
      <mesh
        geometry={nodes.SK_Pelvis_Hi_Dark_Mat_0.geometry}
        material={materials.Dark_Mat}
      />
      <mesh
        geometry={nodes.SK_Pelvis_Hi_Body_Mat_0.geometry}
        material={materials.Body_Mat}
      />
      <mesh
        geometry={nodes.SK_Chest_Hi_Dark_Mat_0.geometry}
        material={materials.Dark_Mat}
      />
      <mesh
        geometry={nodes.SK_Chest_Hi_Dark_Mat_0_1.geometry}
        material={materials.Dark_Mat}
      />
      <mesh
        geometry={nodes.SK_Chest_Hi_Dark_Mat_0_2.geometry}
        material={materials.Dark_Mat}
      />
      <mesh
        geometry={nodes.SK_Chest_Hi_Kashima_Mat_0.geometry}
        material={materials.Kashima_Mat}
      />
      <group
        position={[-65.41, 25.723, -21.488]}
        rotation={[0.231, 0.074, -0.49]}
      >
        <group
          position={[-17.599, 13.02, 30.505]}
          rotation={[-0.46, -0.411, -0.155]}
        >
          <mesh
            geometry={nodes.M_Arm_Lower_Hi_Body_Mat_0.geometry}
            material={materials.Body_Mat}
          />
          <mesh
            geometry={nodes.M_Arm_Lower_Hi_Dark_Mat_0.geometry}
            material={materials.Dark_Mat}
          />
          <mesh
            geometry={nodes.M_Arm_Lower_Hi_Rubber_Mat_0.geometry}
            material={materials.Rubber_Mat}
          />
          <mesh
            geometry={nodes.SK_Arm_Lower_Hi_Dark_Mat_0.geometry}
            material={materials.Dark_Mat}
          />
          <mesh
            geometry={nodes.SK_Arm_Lower_Hi_Rubber_Mat_0.geometry}
            material={materials.Rubber_Mat}
          />
          <mesh
            geometry={nodes.SK_Hand_Hi_Dark_Mat_0.geometry}
            material={materials.Dark_Mat}
          />
          <mesh
            geometry={nodes.SK_Hand_Hi_Body_Mat_0.geometry}
            material={materials.Body_Mat}
          />
        </group>
        <mesh
          geometry={nodes.M_Arm_Upper_Hi_Body_Mat_0.geometry}
          material={materials.Body_Mat}
        />
        <mesh
          geometry={nodes.M_Arm_Upper_Hi_Dark_Mat_0.geometry}
          material={materials.Dark_Mat}
        />
        <mesh
          geometry={nodes.SK_Arm_Upper_Hi_Dark_Mat_0.geometry}
          material={materials.Dark_Mat}
        />
        <mesh
          geometry={nodes.SK_Arm_Upper_Hi_Wires_Mat1_0.geometry}
          material={materials.Wires_Mat1}
        />
        <mesh
          geometry={nodes.SK_Arm_Upper_Hi_Kashima_Mat_0.geometry}
          material={materials.Kashima_Mat}
        />
      </group>
      <group position={[0.095, 0, 1.55]} rotation={[0, 0.122, 0]}>
        <group position={[0.095, 0, -1.55]} rotation={[0, -0.122, 0]}>
          <mesh
            geometry={nodes.M_Leg_Upper_Hi2_Dark_Mat_0.geometry}
            material={materials.Dark_Mat}
          />
          <mesh
            geometry={nodes.M_Leg_Upper_Hi2_Body_Mat_0.geometry}
            material={materials.Body_Mat}
          />
        </group>
        <mesh
          geometry={nodes.SK_Leg_Upper_Hi_Dark_Mat_0.geometry}
          material={materials.Dark_Mat}
        />
        <mesh
          geometry={nodes.SK_Leg_Upper_Hi_Body_Mat_0.geometry}
          material={materials.Body_Mat}
        />
        <mesh
          geometry={nodes.SK_Leg_Upper_Hi_Rubber_Mat_0.geometry}
          material={materials.Rubber_Mat}
        />
        <mesh
          geometry={nodes.M_Leg_Lower_Hi_Dark_Mat_0.geometry}
          material={materials.Dark_Mat}
        />
        <mesh
          geometry={nodes.M_Leg_Lower_Hi_Body_Mat_0.geometry}
          material={materials.Body_Mat}
        />
        <mesh
          geometry={nodes.SK_Leg_Lower_Hi_Dark_Mat_0.geometry}
          material={materials.Dark_Mat}
        />
        <mesh
          geometry={nodes.SK_Leg_Lower_Hi_Wires_Mat1_0.geometry}
          material={materials.Wires_Mat1}
        />
        <mesh
          geometry={nodes.SK_Leg_Lower_Hi_Body_Mat_0.geometry}
          material={materials.Body_Mat}
        />
        <mesh
          geometry={nodes.SK_Foot_Hi_Rubber_Mat_0.geometry}
          material={materials.Rubber_Mat}
        />
        <mesh
          geometry={nodes.SK_Foot_Hi_Dark_Mat_0.geometry}
          material={materials.Dark_Mat}
        />
        <mesh
          geometry={nodes.SK_Foot_Hi_Kashima_Mat_0.geometry}
          material={materials.Kashima_Mat}
        />
      </group>
      <group rotation={[0.231, 0.074, -0.49]}>
        <group rotation={[-0.46, -0.411, -0.155]}>
          <mesh
            geometry={nodes.SK_Arm_Lower_Hi_Dark_Mat_0_1.geometry}
            material={materials.Dark_Mat}
          />
          <mesh
            geometry={nodes.SK_Arm_Lower_Hi_Body_Mat_0.geometry}
            material={materials.Body_Mat}
          />
          <mesh
            geometry={nodes.SK_Arm_Lower_Hi_Wires_Mat1_0.geometry}
            material={materials.Wires_Mat1}
          />
          <mesh
            geometry={nodes.SK_Arm_Lower_Hi_Rubber_Mat_0_1.geometry}
            material={materials.Rubber_Mat}
          />
          <mesh
            geometry={nodes.SK_Hand_Hi_Dark_Mat_0_1.geometry}
            material={materials.Dark_Mat}
          />
          <mesh
            geometry={nodes.SK_Hand_Hi_Wires_Mat1_0.geometry}
            material={materials.Wires_Mat1}
          />
          <mesh
            geometry={nodes.SK_Hand_Hi_Body_Mat_0_1.geometry}
            material={materials.Body_Mat}
          />
        </group>
        <mesh
          geometry={nodes.SK_Arm_Upper_Hi_Dark_Mat_0_1.geometry}
          material={materials.Dark_Mat}
        />
        <mesh
          geometry={nodes.SK_Arm_Upper_Hi_Wires_Mat1_0_1.geometry}
          material={materials.Wires_Mat1}
        />
        <mesh
          geometry={nodes.SK_Arm_Upper_Hi_Body_Mat_0.geometry}
          material={materials.Body_Mat}
        />
        <mesh
          geometry={nodes.SK_Arm_Upper_Hi_Kashima_Mat_0_1.geometry}
          material={materials.Kashima_Mat}
        />
      </group>
      <group rotation={[0, 0.122, 0]}>
        <mesh
          geometry={nodes.SK_Leg_Upper_Hi_Dark_Mat_0_1.geometry}
          material={materials.Dark_Mat}
        />
        <mesh
          geometry={nodes.SK_Leg_Upper_Hi_Body_Mat_0_1.geometry}
          material={materials.Body_Mat}
        />
        <mesh
          geometry={nodes.SK_Leg_Upper_Hi_Wires_Mat1_0.geometry}
          material={materials.Wires_Mat1}
        />
        <mesh
          geometry={nodes.SK_Leg_Upper_Hi_Rubber_Mat_0_1.geometry}
          material={materials.Rubber_Mat}
        />
        <mesh
          geometry={nodes.SK_Leg_Upper_Hi_Chrome_Mat_0.geometry}
          material={materials.Chrome_Mat}
        />
        <mesh
          geometry={nodes.SK_Leg_Lower_Hi_Dark_Mat_0_1.geometry}
          material={materials.Dark_Mat}
        />
        <mesh
          geometry={nodes.SK_Leg_Lower_Hi_Wires_Mat1_0_1.geometry}
          material={materials.Wires_Mat1}
        />
        <mesh
          geometry={nodes.SK_Leg_Lower_Hi_Body_Mat_0_1.geometry}
          material={materials.Body_Mat}
        />
        <mesh
          geometry={nodes.SK_Foot_Hi_Rubber_Mat_0_1.geometry}
          material={materials.Rubber_Mat}
        />
        <mesh
          geometry={nodes.SK_Foot_Hi_Dark_Mat_0_1.geometry}
          material={materials.Dark_Mat}
        />
        <mesh
          geometry={nodes.SK_Foot_Hi_Kashima_Mat_0_1.geometry}
          material={materials.Kashima_Mat}
        />
      </group>
    </group>
  )
}

useGLTF.preload(path)
